### ISSUE TITLE
Error: No address associated with hostname, errno = 7

### ISSUE THREAD

**Issue by cocvu99** [rrafush/weather_app#5]
Hi, I just installed file .apk on my Samsung A9. I have connected Wifi internet, filled somes city name. And I dont know why it appeared this bug. Could you guys explain what am wrong? Or fix that? Or tell me a solution to fix that? 
Thank you!
Regards.
![269336759_494339708679722_3504341621798319360_n](https://user-images.githubusercontent.com/41517959/147673828-d0591541-f771-4195-9b39-1c53c644bdbf.jpg)

**Comment by rrafush** [comment]
first of all, I'm so sorry about the enourmous delay, I feel very flattered that you installed my app! This is an app I made for study and it happens that it's been a while now the API doesn't exist, it was missing a permission before and that was fixed, but I'm right now trying to find a nice API and refactor most of the code :) thanks!!!
